# Generated by Django 2.1.4 on 2020-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_device_question_user_openid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_question',
            name='q_status',
        ),
        migrations.AddField(
            model_name='device_question',
            name='q_dealing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device_question',
            name='q_over',
            field=models.BooleanField(default=False),
        ),
    ]
