# Generated by Django 2.1.4 on 2020-03-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_auto_20200312_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_question',
            name='user_openid',
            field=models.CharField(max_length=256),
        ),
    ]
