# Generated by Django 2.1.4 on 2020-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('groups', models.OneToOneField(on_delete=True, to='auth.Group', verbose_name='group_power')),
            ],
            options={
                'verbose_name_plural': 'group_change',
            },
        ),
    ]
