# Generated by Django 2.1.4 on 2020-03-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_rolecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolecode',
            name='code',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
